
import React from 'react';
import { BuildTutorial as TutorialType } from '../types';
import { downloadFile } from '../utils/exportUtils';

interface BuildTutorialProps {
  tutorial: TutorialType;
  structureName: string;
}

const BuildTutorial: React.FC<BuildTutorialProps> = ({ tutorial, structureName }) => {
  const handleDownloadPDF = () => {
    const safeName = structureName || 'structure';
    let content = `====================================================\n`;
    content += `        🛠️ STEP-BY-STEP BUILD GUIDE\n`;
    content += `====================================================\n\n`;
    content += `STRUCTURE: ${safeName}\n`;
    content += `DIFFICULTY: ${tutorial.difficulty || 'Normal'}\n`;
    content += `ESTIMATED TIME: ${tutorial.totalEstimatedTime || 'Unknown'}\n`;
    content += `RECOMMENDED TOOLS: ${(tutorial.recommendedTools || []).join(', ')}\n\n`;
    content += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;

    (tutorial.phases || []).forEach((phase, pIndex) => {
      content += `PHASE ${pIndex + 1}: ${(phase.name || 'Phase').toUpperCase()}\n`;
      content += `Estimated Time: ${phase.estimatedTime || 'N/A'}\n\n`;
      
      (phase.steps || []).forEach((step, sIndex) => {
        content += `STEP ${pIndex + 1}.${sIndex + 1} - ${step.title || 'Step'}\n`;
        content += `• ${step.description || ''}\n`;
        if (step.coordinates) content += `• Coordinates: ${step.coordinates}\n`;
        if (step.blocksNeeded) content += `• Blocks Needed: ${step.blocksNeeded}\n`;
        content += `\n`;
      });

      content += `✅ CHECKPOINT: ${phase.checkpoint || 'Complete'}\n\n`;
      content += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;
    });

    content += `🎉 CONGRATULATIONS!\n`;
    content += `Your ${safeName} is complete!\n\n`;
    content += `Generated by AI Minecraft Builder`;

    const fileName = `${safeName.toLowerCase().replace(/\s+/g, '_')}_guide.txt`;
    downloadFile(content, fileName, 'text/plain');
  };

  return (
    <div className="bg-slate-800/60 backdrop-blur-md p-6 rounded-3xl border border-slate-700 shadow-xl h-full flex flex-col overflow-hidden">
      <div className="flex justify-between items-start mb-6 shrink-0">
        <div>
          <h3 className="text-xl font-black text-emerald-400 flex items-center gap-3 tracking-tight">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
            </svg>
            Manual Guide
          </h3>
          <p className="text-[10px] text-slate-500 font-black uppercase tracking-[0.2em] mt-1">Procedural Steps</p>
        </div>
        <div className="bg-slate-900 px-3 py-1.5 rounded-xl border border-slate-700">
          <div className="text-[8px] font-black text-slate-500 uppercase tracking-widest text-center">Skill</div>
          <div className="text-amber-400 font-black text-[10px] uppercase text-center">{tutorial.difficulty || 'Expert'}</div>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-3 mb-6 shrink-0">
        <div className="bg-slate-950/50 p-3 rounded-2xl border border-slate-800">
          <div className="text-[8px] uppercase font-black text-slate-600 mb-1 tracking-widest">Est. Duration</div>
          <div className="text-slate-200 text-xs font-bold">{tutorial.totalEstimatedTime || 'N/A'}</div>
        </div>
        <div className="bg-slate-950/50 p-3 rounded-2xl border border-slate-800 flex flex-col">
          <div className="text-[8px] uppercase font-black text-slate-600 mb-1 tracking-widest">Prep Items</div>
          <div className="text-slate-300 text-[9px] leading-tight flex flex-wrap gap-1">
            {(tutorial.recommendedTools || ['Pickaxe', 'Scaffolding']).slice(0, 3).map((tool, i) => (
              <span key={i} className="bg-slate-900 px-1.5 py-0.5 rounded border border-slate-700">{tool}</span>
            ))}
          </div>
        </div>
      </div>

      <div className="space-y-6 overflow-y-auto pr-2 custom-scrollbar flex-grow">
        {(tutorial.phases || []).map((phase, pIndex) => (
          <div key={pIndex} className="relative pl-6 border-l-2 border-slate-700 py-1">
            <div className="absolute -left-3.5 top-0 w-7 h-7 rounded-full bg-slate-900 border-2 border-slate-700 flex items-center justify-center text-[10px] font-black text-emerald-400 shadow-lg">
              {pIndex + 1}
            </div>
            
            <div className="mb-4">
              <h4 className="text-xs font-black text-slate-100 uppercase tracking-wider">{phase.name || 'Structural Phase'}</h4>
              <span className="text-[9px] text-slate-600 font-mono font-bold">{phase.estimatedTime || '30-60 mins'}</span>
            </div>

            <div className="space-y-3">
              {(phase.steps || []).map((step, sIndex) => (
                <div key={sIndex} className="bg-slate-900/60 p-4 rounded-2xl border border-slate-800/50 hover:border-slate-700 transition-colors">
                  <h5 className="text-[11px] font-black text-emerald-500 mb-1.5 uppercase tracking-tight">{step.title || 'Action Step'}</h5>
                  <p className="text-[10px] text-slate-400 leading-relaxed font-medium mb-3">{step.description || ''}</p>
                  
                  {(step.coordinates || step.blocksNeeded) && (
                    <div className="flex flex-wrap gap-2 mt-auto">
                      {step.coordinates && (
                        <div className="px-2 py-1 bg-slate-950/80 rounded-lg text-[8px] font-mono text-slate-500 border border-slate-800">
                          {step.coordinates}
                        </div>
                      )}
                      {step.blocksNeeded && (
                        <div className="px-2 py-1 bg-slate-950/80 rounded-lg text-[8px] font-mono text-emerald-500/60 border border-slate-800">
                          {step.blocksNeeded}
                        </div>
                      )}
                    </div>
                  )}
                </div>
              ))}
            </div>

            <div className="mt-4 p-3 bg-emerald-500/5 border border-emerald-500/10 rounded-xl flex items-center gap-3">
              <div className="w-5 h-5 rounded-full bg-emerald-500/20 flex items-center justify-center shrink-0 border border-emerald-500/30">
                <svg className="w-3 h-3 text-emerald-400" fill="currentColor" viewBox="0 0 20 20"><path d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"/></svg>
              </div>
              <p className="text-[9px] font-bold text-emerald-400/80 leading-tight uppercase tracking-widest">
                {phase.checkpoint || 'Verification Complete'}
              </p>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-6 text-center pt-5 border-t border-slate-700/50 shrink-0">
        <button 
          onClick={handleDownloadPDF}
          className="w-full py-3 bg-slate-900 hover:bg-slate-800 text-emerald-400 transition-all rounded-2xl border border-slate-700 text-[10px] uppercase tracking-[0.2em] font-black flex items-center justify-center gap-3 hover:scale-[1.02]"
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
          Export Build Map
        </button>
      </div>
    </div>
  );
};

export default BuildTutorial;
